#!/bin/bash

bl_device=/sys/class/backlight/intel_backlight/brightness
if [ "$1" == "g" ];then
	cat $bl_device
fi

if [ "$1" == "u" ];then
	echo $(($(cat $bl_device)+10)) | sudo tee $bl_device
fi

if [ "$1" == "d" ];then
	echo $(($(cat $bl_device)-10)) | sudo tee $bl_device
fi


if [ "$1" == "s" ];then
	echo $2 | sudo tee $bl_device
fi

